services:
  chat-bot:
    build: .
    container_name: php_chat_bot
    restart: "no"
    env_file:
      - .env
    volumes:
      - .:/var/www
      - /var/www/vendor/ # Keeps container vendor separate from host
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
